### ISSUE TITLE
Support hotkeys same as N1MM & Morse Runner

### ISSUE THREAD

**Issue by stianeklund** [w9cf/cwsim#5]
There are certain hotkeys used by N1MM & Morse Runner (and similar):

* `\` Same as F1
* `;` Exchange (Same as F2)
* `.` TU same as F3

These are handy because you don't have to reach for the F-keys as much.
Would this be something you can consider implementing?

**Comment by w9cf** [comment]
I think I have added these in current release 0.9 so they work as in  Morse runner. Please let me know  if something does not work.

I learned computer contest logging using TR log, which has always used enter sends message. Since enter send message was ported to N1MM+, I use it there as well, and never use these hot keys; I didn't bother to add them originally.

When using N1MM+, \ switches rig receive focus for SO2R, and switches to the second vfo window for SO2V.  I added here as an alternative F1 key as requested.

73 Kevin w9cf
